baseURL = "https://jovial-goodall-56785c.netlify.app/"
languageCode = "en-us"
title = "Project One"
theme = "project-1"
paginate = 50
sectionPagesMenu = "main"


[params]
    description = "Project One"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!

[taxonomies]
    pcb = "pcb"